#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportWCF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SPORT_DB")]
	public partial class SPORT_LINK_DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBEST_PLAYER(BEST_PLAYER instance);
    partial void UpdateBEST_PLAYER(BEST_PLAYER instance);
    partial void DeleteBEST_PLAYER(BEST_PLAYER instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertGAME(GAME instance);
    partial void UpdateGAME(GAME instance);
    partial void DeleteGAME(GAME instance);
    partial void InsertGAME_IMAGE(GAME_IMAGE instance);
    partial void UpdateGAME_IMAGE(GAME_IMAGE instance);
    partial void DeleteGAME_IMAGE(GAME_IMAGE instance);
    partial void InsertGAME_STAT(GAME_STAT instance);
    partial void UpdateGAME_STAT(GAME_STAT instance);
    partial void DeleteGAME_STAT(GAME_STAT instance);
    partial void InsertGAME_TICKET(GAME_TICKET instance);
    partial void UpdateGAME_TICKET(GAME_TICKET instance);
    partial void DeleteGAME_TICKET(GAME_TICKET instance);
    partial void InsertLEAGUE(LEAGUE instance);
    partial void UpdateLEAGUE(LEAGUE instance);
    partial void DeleteLEAGUE(LEAGUE instance);
    partial void InsertLEAGUE_IMAGE(LEAGUE_IMAGE instance);
    partial void UpdateLEAGUE_IMAGE(LEAGUE_IMAGE instance);
    partial void DeleteLEAGUE_IMAGE(LEAGUE_IMAGE instance);
    partial void InsertLEAGUES_GAME(LEAGUES_GAME instance);
    partial void UpdateLEAGUES_GAME(LEAGUES_GAME instance);
    partial void DeleteLEAGUES_GAME(LEAGUES_GAME instance);
    partial void InsertLOG(LOG instance);
    partial void UpdateLOG(LOG instance);
    partial void DeleteLOG(LOG instance);
    partial void InsertSPORT(SPORT instance);
    partial void UpdateSPORT(SPORT instance);
    partial void DeleteSPORT(SPORT instance);
    partial void InsertSPORT_LEAGUE(SPORT_LEAGUE instance);
    partial void UpdateSPORT_LEAGUE(SPORT_LEAGUE instance);
    partial void DeleteSPORT_LEAGUE(SPORT_LEAGUE instance);
    partial void InsertTEAMIMAGE(TEAMIMAGE instance);
    partial void UpdateTEAMIMAGE(TEAMIMAGE instance);
    partial void DeleteTEAMIMAGE(TEAMIMAGE instance);
    partial void InsertTEAMPLAYER(TEAMPLAYER instance);
    partial void UpdateTEAMPLAYER(TEAMPLAYER instance);
    partial void DeleteTEAMPLAYER(TEAMPLAYER instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    partial void InsertUSERIMAGE(USERIMAGE instance);
    partial void UpdateUSERIMAGE(USERIMAGE instance);
    partial void DeleteUSERIMAGE(USERIMAGE instance);
    partial void InsertVENUE(VENUE instance);
    partial void UpdateVENUE(VENUE instance);
    partial void DeleteVENUE(VENUE instance);
    #endregion
		
